[package]
name = "litedoc-browser"
version = "0.1.1"
description = "A lightweight local HTML and Markdown browser."
authors = ["LiteDoc Browser"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = ["protocol-asset"] }
url = "2"
